lista = [int(i) for i in input().split()]
quantos = lista.count(0)
print("0",quantos)
quantos = lista.count(1)
print("1",quantos)
quantos = lista.count(2)
print("2",quantos)
quantos = lista.count(3)
print("3",quantos)
quantos = lista.count(4)
print("4",quantos)
quantos = lista.count(5)
print("5",quantos)
quantos = lista.count(6)
print("6",quantos)
quantos = lista.count(7)
print("7",quantos)
quantos = lista.count(8)
print("8",quantos)
quantos = lista.count(9)
print("9",quantos)
